name: dotnet package

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore .\PDFonty\PDFonty.sln
      - name: Build
        run: dotnet publish -p:PublishReadyToRun=true -p:PublishSingleFile=true --no-self-contained -r win-x64 -c Release .\PDFonty\PDFonty.sln
      - name: Test
        run: dotnet test --no-restore --verbosity normal .\PDFonty\PDFonty.sln
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: PDFonty-Release
          path: PDFonty\bin\Release\net8.0-windows7.0\win-x64\publish\
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "最新编译版本-Github Actions云构建"
          files: |
            PDFonty/bin/Release/net7.0-windows/win-x64/publish/PDFonty.exe
